version: '3.3'

services:
  wallabag:
    image: wallabag/wallabag
    container_name: wallabag
    restart: unless-stopped
    ports:
      - "8484:80"
    environment:
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_sqlite
      - SYMFONY__ENV__DATABASE_PATH=/var/www/wallabag/data/wallabag.sqlite
      - SYMFONY__ENV__DOMAIN_NAME=http://localhost:8484
      - SYMFONY__ENV__SERVER_NAME=wallabag
    volumes:
      - H:/Docker/wallabag:/var/www/wallabag/data

#Default username & password: wallabag
