services:
  prunemate:
    image: anoniemerd/prunemate:latest  # Supports amd64 and arm64
    container_name: prunemate
    ports:
      - "7676:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /DATA/AppData/prunemate/logs:/var/log
      - /DATA/AppData/prunemate/config:/config
    environment:
      - PRUNEMATE_TZ=Asia/Dhaka
      - PRUNEMATE_TIME_24H=true 
    restart: unless-stopped
