# compose.yaml
services:
  yubal:
    image: ghcr.io/guillevc/yubal:latest
    container_name: yubal
    user: 1000:1000
    ports:
      - 8000:8000
    environment:
      YUBAL_SCHEDULER_CRON: "0 0 * * *"
      YUBAL_TZ: UTC
    volumes:
      - /media/devmon/Seagate/yubal/data:/app/data
      - /media/devmon/Seagate/yubal/config:/app/config
    restart: unless-stopped
