services:
  yamtrack:
    container_name: yamtrack
    image: ghcr.io/fuzzygrim/yamtrack
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - TZ=Asia/Dhaka
      - SECRET=t1U2xAiz7lxjyTz689q8W+aSg3B0SbaoC30ZQx+LvJrod7jkocA0d+0mgi0tUct8
      - REDIS_URL=redis://yamtrack-redis:6379
      #- STEAM_API_KEY= Add yours
    volumes:
      - /DATA/AppData/yamtrack:/yamtrack/db
    ports:
      - "4003:8000"
    networks:
      - yamtrack_net

  redis:
    container_name: yamtrack-redis
    image: redis:8-alpine
    restart: unless-stopped
    volumes:
      - /DATA/AppData/yamtrack/redis:/data
    networks:
      - yamtrack_net

volumes:
  redis_data:

networks:
  yamtrack_net:
    driver: bridge

