version: '3.8'

services:
  yamtrack:
    image: ghcr.io/yamtrack/yamtrack:latest
    container_name: yamtrack
    ports:
      - "4003:8000"
    volumes:
      - /DATA/AppData/yamtrack:/data
    environment:
      - TZ=Asia/Dhaka
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:8-alpine
    container_name: yamtrack_redis
    restart: unless-stopped
