services:
  dockpeek:
    image: ghcr.io/dockpeek/dockpeek:latest
    container_name: dockpeek
    environment:
      - SECRET_KEY=3b854764-1850-4c6b-9c14-793eb89eb9d6 # Required: Set a secure secret key
      - USERNAME=admin # username
      - PASSWORD=password # password
    ports:
      - "9595:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - H:/Docker/dockpeek:/app/data
    restart: unless-stopped
