services:
  dockpeek:
    image: ghcr.io/dockpeek/dockpeek:latest
    container_name: dockpeek
    environment:
      - SECRET_KEY=your_secure_secret_key # Required: Set a secure secret key
      - USERNAME=admin # username
      - PASSWORD=password # password
    ports:
      - "9595:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - H:/Docker/dockpeek:/app/data
    restart: unless-stopped
