services:
  lidify:
    image: chevron7locked/kima:v1.5.0
    container_name: Kima
    ports:
      - "3030:3030"
    volumes:
      - /media/devmon/Seagate/Music:/music
      - /DATA/AppData/Kima/data:/data
    environment:
      - TZ=Asia/Dhaka
    restart: unless-stopped
