services:
  lidify:
    image: chevron7locked/lidify:latest
    container_name: lidify
    ports:
      - "3030:3030"
    volumes:
      - /media/devmon/Seagate/Music:/music
      - /DATA/AppData/Lidify/postgres:/data
    environment:
      - TZ=Asia/Dhaka
    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: unless-stopped
