services:
  lidify:
    image: chevron7locked/kima:v1.5.0
    container_name: lidify
    ports:
      - "3030:3030"
    volumes:
      - /media/devmon/Seagate/Music:/music
      - /DATA/AppData/Lidify/postgres:/data/postgres
      - /DATA/AppData/Lidify/Download:/downloads
    environment:
      - TZ=Asia/Dhaka
    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: unless-stopped

