version: '3.7'

services:
  esphome:
    image: esphome/esphome:latest
    container_name: esphome
    restart: unless-stopped
    ports:
      - "6052:6052"  # web dashboard
    volumes:
      - H:/Docker/esphome:/config
    environment:
      - TZ=Asia/Dhaka
